language: go

go:
  - 1.4
  - 1.5
  - 1.6

install:
  - go get github.com/123hurray/netroxy/apps/netroxy_server
  - go get github.com/123hurray/netroxy/apps/netroxy_client
notifications:
  email: false